/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Backend.InputValidator;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jcj
 */
public class AddTeacherForm extends javax.swing.JFrame
{

    /**
     * Creates new form NewJFrame
     */
    public AddTeacherForm()
    {
        initComponents();
        updateProgressBar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        registerClassToggleButton = new javax.swing.JToggleButton();
        numGradesSlider = new javax.swing.JSlider();
        correctInputsProgressBar = new javax.swing.JProgressBar();
        extramuralSpinner = new javax.swing.JSpinner();
        extramuralSpinner.setBackground(Color.WHITE);
        submitButton = new javax.swing.JButton();
        screenTitleLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        fullnameField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        birthdayLabel = new javax.swing.JLabel();
        numGradesLabel = new javax.swing.JLabel();
        extramuralsLabel = new javax.swing.JLabel();
        correctInputsLabel = new javax.swing.JLabel();
        fullnameLabel = new javax.swing.JLabel();
        birthdayField = new javax.swing.JTextField();
        extraM_WarningLabel = new javax.swing.JLabel();
        name_warningText = new javax.swing.JTextField();
        birthday_warningText = new javax.swing.JTextField();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerClassToggleButton.setBackground(jPanel1.getBackground());
        registerClassToggleButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registerClassToggleButton.setForeground(new java.awt.Color(102, 102, 102));
        registerClassToggleButton.setText("Register Class");
        registerClassToggleButton.setRolloverEnabled(false);
        jPanel1.add(registerClassToggleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 110, 30));

        numGradesSlider.setForeground(new java.awt.Color(102, 153, 255));
        numGradesSlider.setMajorTickSpacing(1);
        numGradesSlider.setMaximum(5);
        numGradesSlider.setMinimum(1);
        numGradesSlider.setPaintLabels(true);
        numGradesSlider.setPaintTicks(true);
        numGradesSlider.setSnapToTicks(true);
        numGradesSlider.setValue(1);
        jPanel1.add(numGradesSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 250, -1));

        correctInputsProgressBar.setBackground(jPanel1.getBackground());
        correctInputsProgressBar.setForeground(new java.awt.Color(0, 51, 102));
        correctInputsProgressBar.setMaximum(5);
        correctInputsProgressBar.setMinimum(1);
        correctInputsProgressBar.setToolTipText("");
        correctInputsProgressBar.setBorder(null);
        jPanel1.add(correctInputsProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 230, 20));

        extramuralSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        extramuralSpinner.setOpaque(true);
        jPanel1.add(extramuralSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 70, 30));

        submitButton.setBackground(new java.awt.Color(0, 51, 102));
        submitButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitButton.setText("Submit");
        submitButton.setEnabled(false);
        jPanel1.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 100, -1));

        screenTitleLabel.setBackground(getBackground());
        screenTitleLabel.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        screenTitleLabel.setForeground(new java.awt.Color(0, 51, 102));
        screenTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        screenTitleLabel.setText("Add Teacher Screen");
        jPanel1.add(screenTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 40));

        jSeparator1.setForeground(new java.awt.Color(255, 204, 102));
        jSeparator1.setAlignmentY(0.0F);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, 404, 10));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 45, 10, 400));

        fullnameField.setBackground(jPanel1.getBackground());
        fullnameField.setText("e.g. Clifton Lloyd Bartholomew");
        fullnameField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                fullnameFieldKeyReleased(evt);
            }
        });
        jPanel1.add(fullnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 230, -1));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        birthdayLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        birthdayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        birthdayLabel.setText("Birthday:");

        numGradesLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numGradesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numGradesLabel.setText("Number of Grades taught ");

        extramuralsLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        extramuralsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        extramuralsLabel.setText("Extramural Activities");

        correctInputsLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        correctInputsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        correctInputsLabel.setText("Fields entered correctly:");

        fullnameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fullnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullnameLabel.setText("Full Name:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(extramuralsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(numGradesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(birthdayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fullnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(correctInputsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(fullnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(birthdayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(numGradesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(extramuralsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(correctInputsLabel)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 160, 390));

        birthdayField.setBackground(jPanel1.getBackground());
        birthdayField.setText("dd/MM/YYYY");
        birthdayField.setToolTipText("Enter in format \"dd/MM/YYYY\"");
        birthdayField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                birthdayFieldKeyReleased(evt);
            }
        });
        jPanel1.add(birthdayField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 230, -1));

        extraM_WarningLabel.setBackground(java.awt.Color.red);
        extraM_WarningLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        extraM_WarningLabel.setForeground(Color.GREEN.darker());
        extraM_WarningLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        extraM_WarningLabel.setText("Valid");
        jPanel1.add(extraM_WarningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 70, 20));

        name_warningText.setEditable(false);
        name_warningText.setBackground(jPanel1.getBackground());
        name_warningText.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        name_warningText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        name_warningText.setBorder(null);
        jPanel1.add(name_warningText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 230, 40));

        birthday_warningText.setEditable(false);
        birthday_warningText.setBackground(jPanel1.getBackground());
        birthday_warningText.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        birthday_warningText.setBorder(null);
        birthday_warningText.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                birthday_warningTextActionPerformed(evt);
            }
        });
        jPanel1.add(birthday_warningText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 230, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void checkEMValidity()
    {
        String numExtraMStr = ""+ extramuralSpinner.getValue();
        
        if (InputValidator.isCorrectDataType(numExtraMStr, "Integer"))
        {
            extraMuralCorrect = true;
            extraM_WarningLabel.setText("Valid");
            extraM_WarningLabel.setForeground(Color.GREEN.darker());
        }else{
            extraMuralCorrect = false;
            extraM_WarningLabel.setText("Invalid");
            extraM_WarningLabel.setForeground(Color.RED);
        }
        updateProgressBar();
    }
    private void fullnameFieldKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_fullnameFieldKeyReleased
    {//GEN-HEADEREND:event_fullnameFieldKeyReleased
        // TODO add your handling code here:
        String fullname = fullnameField.getText();
        
        nameCorrect = false;
        name_warningText.setForeground(Color.RED);
        
        if (InputValidator.isLength(fullname, 3, 100))
            if (InputValidator.isFormattedName(fullname))
                if (InputValidator.hasNameCapitals(fullname))
                    if (InputValidator.isCorrectDataType(fullname, "String")) 
                    {
                        nameCorrect = true;
                        name_warningText.setText("Valid");
                        name_warningText.setForeground(Color.GREEN.darker());
                    }else {
                        name_warningText.setText("Do not use symbols or numbers.");
                    }
                else name_warningText.setText("Use Capital Letters for Name and Surname.");
            else name_warningText.setText("Enter Name AND Surname.");
        else name_warningText.setText("Enter at least 3 characters.");
            
         updateProgressBar();
    }//GEN-LAST:event_fullnameFieldKeyReleased

    private void birthdayFieldKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_birthdayFieldKeyReleased
    {//GEN-HEADEREND:event_birthdayFieldKeyReleased
        // TODO add your handling code here:
         String birthdayStr = birthdayField.getText();
        birthdayCorrect = false;
        birthday_warningText.setForeground(Color.RED);
        
        if (birthdayStr.length() == 10)
            if (InputValidator.isCorrectDataType(birthdayStr, "Date"))
            {
                if (InputValidator.isFormattedDate(birthdayStr) )
                {
                    if( InputValidator.isValidAge(birthdayStr))
                    {
                        birthdayCorrect = true;
                        birthday_warningText.setText("Valid");
                        birthday_warningText.setForeground(Color.GREEN.darker());
                    }else 
                    {
                        birthday_warningText.setText("Age must be in range 18 - 120");
                    }
                }else {
                    birthday_warningText.setText("Enter a valid date as dd/MM/yyyy");
                }
            }else {
            birthday_warningText.setText("Use only numbers and '/'");
            }
        else birthday_warningText.setText("Must be exactly 10 characters long.");
        
        updateProgressBar();
    }//GEN-LAST:event_birthdayFieldKeyReleased

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel1MouseMoved
    {//GEN-HEADEREND:event_jPanel1MouseMoved
        // TODO add your handling code here:
        checkEMValidity();
    }//GEN-LAST:event_jPanel1MouseMoved

    private void birthday_warningTextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_birthday_warningTextActionPerformed
    {//GEN-HEADEREND:event_birthday_warningTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthday_warningTextActionPerformed
    public void updateProgressBar()
    {
        int numCorrect = 2;
        
        boolean [] varArray = {nameCorrect, birthdayCorrect, extraMuralCorrect};
        
        for (boolean b : varArray) 
        {
            if (b) numCorrect++;
        }
        
        if (numCorrect == 5) 
        {
            submitButton.setEnabled(true);
            correctInputsProgressBar.setForeground(Color.GREEN.darker());
        }else correctInputsProgressBar.setForeground(jPanel2.getBackground());
        correctInputsProgressBar.setValue(numCorrect);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            javax.swing.UIManager.setLookAndFeel("com.formdev.flatlaf.FlatDarkLaf");
            
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(AddTeacherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(AddTeacherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(AddTeacherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(AddTeacherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new AddTeacherForm().setVisible(true);
            }
        });
    }

    public boolean birthdayCorrect;
    public boolean extraMuralCorrect = true;
    public boolean nameCorrect;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField birthdayField;
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.JTextField birthday_warningText;
    private javax.swing.JLabel correctInputsLabel;
    private javax.swing.JProgressBar correctInputsProgressBar;
    private javax.swing.JLabel extraM_WarningLabel;
    private javax.swing.JSpinner extramuralSpinner;
    private javax.swing.JLabel extramuralsLabel;
    private javax.swing.JTextField fullnameField;
    private javax.swing.JLabel fullnameLabel;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField name_warningText;
    private javax.swing.JLabel numGradesLabel;
    private javax.swing.JSlider numGradesSlider;
    private javax.swing.JToggleButton registerClassToggleButton;
    private javax.swing.JLabel screenTitleLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
